apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: app-ingress 
spec: 
  ingressClassName: nginx 
  rules: 
    - host: http://a584ae95e621b422bb2456ce6887076e-81406a51b4c1952b.elb.ap-south-1.amazonaws.com
      http: 
        paths: 
          - path: / 
            pathType: Prefix 
            backend: 
              service: 
                name: frontend-svc 
                port: 
                  number: 80 
          - path: /api 
            pathType: Prefix 
            backend: 
              service: 
                name: backend-svc 
                port: 
                  number: 8080