apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: frontend-deployment 
  labels: 
    app: frontend 
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: frontend
  template: 
    metadata: 
      labels: 
        app: frontend 
    spec: 
      containers: 
        - name: frontend-container
          image: 262349351040.dkr.ecr.ap-south-1.amazonaws.com/frontend:14
kind: Deployment 
metadata: 
  name: frontend-deployment 
  labels: 
    app: frontend 
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: frontend
  template: 
    metadata: 
      labels: 
        app: frontend 
    spec: 
      containers: 
        - name: frontend-container
          image: 262349351040.dkr.ecr.ap-south-1.amazonaws.com/frontend:14
          ports: 
            - containerPort: 80

          resources: 
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits: 
              cpu: "200m"
              memory: "256Mi"
          
          ports: 
            - containerPort: 80

          resources: 
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits: 
              cpu: "200m"
              memory: "256Mi"
          