apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: easycrud-backend
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vaishnavigulhane19/EasyCRUD.git
    targetRevision: main
    path: k8s/backend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true